### PR TITLE
Feature/cdci

### PR DESCRIPTION
**Pull request by florianporada**
Added some deployment files and a working dockerfile

### CODE REVIEW

**Comment by tdurand** [comment]
Thanks ! I'll work on the website early next week and we will be able to have a static export of it (no need to run node on a server). This might cause to change a bit the deployment if we want to be fully static. I'll let you know when ready

**Comment by tdurand** [comment]
PS: we could also use github pages and link the domain directly to the github pages if we want.

**Comment by florianporada** [comment]
We could try to use github actions to trigger the build - in that way we would bypass the whole deployment structure. Let's try :)

**Comment by tdurand** [comment]
I'll ping you next week once I have the static export npm task ready.

**Comment by florianporada** [comment]
@tdurand I just updated the deployment files. 
I'll leave it in our pipeline since beta access to github actions is not there yet.

**Pull request merged**
